<strong>Factors Contributing to House Prices in the United States</strong><br>
<strong>Team Members:</strong> Brody Hughson, Cesar Fontanelli, Marris Jones, Pedro Liriano, and Jeremiah Tatum

<strong>Abstract</strong><br>
This project has been commenced with the goal of identifying the major factors contributing to home/rental prices across the United States. Additionally, this project is being conducted in the hopes of identifying where home conditions and prices are optimal for working and middle class people across the country. Factors and data that will be considered include population density, home quality, crime rates, regulations on home construction/zoning, zoning and residential permit counts by county, etc. Datasets from which these factors will be analyzed include U.S. Census population datasets, Zillow Home Value Index datasets, a Residential Housing Permits by County dataset, and more. The datasets will be cleaned of duplicate records, and records that are primarily (or in some cases completely) composed of null fields. In some cases, dataset column names may be changed to make them easier to understand. Once data cleaning has been completed, the datasets will be compiled where appropriate, and analyzed to identify common statistical descriptions (e.g. min, max, mean, median) as well as the correlation between various variables. The data will be grouped by state, and gross statistical outliers will either be ignored or grouped into their own datasets where appropriate. Once data analysis is complete, a machine learning model may be trained on the dataset to better determine the relationship between factors, and how the impact of various factors may vary in different environments (e.g. high/low-income neighborhoods, high/low crime areas, rural/urban areas, etc.). Finally, the findings of the project will be presented with charts accompanied with explanations of the charts, and their associated findings.

In [1]:
#Imports
import pandas as pd
from altair import Chart, X, Y, Color, Scale
import altair as alt

<strong>Data Retrieval and Initial Exploratory Analysis</strong>

In [2]:
#Load data U.S. Population by county 2020-2024 source: https://www.census.gov/data/tables/time-series/demo/popest/2020s-total-cities-and-towns.html
pop_df = pd.read_csv('https://www2.census.gov/programs-surveys/popest/datasets/2020-2024/cities/totals/sub-est2024.csv', encoding='latin-1')
pop_df.head()

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024
0,40,1,0,0,0,0,0,A,Alabama,Alabama,5025369,5033094,5049196,5076181,5117673,5157699
1,162,1,0,124,0,0,0,A,Abbeville city,Alabama,2349,2349,2329,2328,2337,2370
2,162,1,0,460,0,0,0,A,Adamsville city,Alabama,4393,4381,4315,4251,4204,4181
3,162,1,0,484,0,0,0,A,Addison town,Alabama,661,659,665,670,669,676
4,162,1,0,676,0,0,0,A,Akron town,Alabama,229,228,229,226,229,233

In [62]:
#Exploratory Analysis on Population
#Create filtered df that contains total population by city (SUMLEV = 162)
city_pop_df = pop_df[pop_df["SUMLEV"] == 162].copy()
city_pop_df = city_pop_df.reset_index(drop=True)
#Remove cities with less than 1000 population
print(city_pop_df.shape)
city_pop_df = city_pop_df[city_pop_df["POPESTIMATE2020"] > 100000].reset_index(drop=True)
print(city_pop_df.shape)
#Describe city_pop_df
city_pop_df[["POPESTIMATE2020", "POPESTIMATE2021", "POPESTIMATE2022", "POPESTIMATE2023", "POPESTIMATE2024"]].describe()

(19479, 16)
(323, 16)

,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024
count,3.230000e+02,3.230000e+02,3.230000e+02,3.230000e+02,3.230000e+02
mean,2.994445e+05,2.977475e+05,2.988574e+05,3.010314e+05,3.040163e+05
std,5.911474e+05,5.762745e+05,5.725217e+05,5.755502e+05,5.816003e+05
min,1.000650e+05,9.924300e+04,9.816400e+04,9.858800e+04,9.823000e+04
25%,1.187560e+05,1.179695e+05,1.204045e+05,1.212285e+05,1.222045e+05
50%,1.593280e+05,1.583500e+05,1.597760e+05,1.604910e+05,1.633040e+05
75%,2.672095e+05,2.705615e+05,2.743825e+05,2.761295e+05,2.775815e+05
max,8.740306e+06,8.453772e+06,8.356179e+06,8.390888e+06,8.478072e+06

In [65]:
#Trend line of population per year by quartile
#Create subdataframes for each quartile of city_pop_df
city_pop_q1_df = city_pop_df[city_pop_df["POPESTIMATE2020"] <= 1.187560e+05].reset_index(drop=True)
city_pop_q2_df = city_pop_df[(city_pop_df["POPESTIMATE2020"] <= 1.593280e+05) & (city_pop_df["POPESTIMATE2020"] > 1.187560e+05)].reset_index(drop=True)
city_pop_q3_df = city_pop_df[(city_pop_df["POPESTIMATE2020"] <= 2.672095e+05) & (city_pop_df["POPESTIMATE2020"] > 1.593280e+05)].reset_index(drop=True)
city_pop_q4_df = city_pop_df[city_pop_df["POPESTIMATE2020"] > 2.672095e+05].reset_index(drop=True)
#Create trend series of averages per year
pop_trend_q1 = city_pop_q1_df[["POPESTIMATE2020", "POPESTIMATE2021", "POPESTIMATE2022", "POPESTIMATE2023", "POPESTIMATE2024"]].mean()
pop_trend_q2 = city_pop_q2_df[["POPESTIMATE2020", "POPESTIMATE2021", "POPESTIMATE2022", "POPESTIMATE2023", "POPESTIMATE2024"]].mean()
pop_trend_q3 = city_pop_q3_df[["POPESTIMATE2020", "POPESTIMATE2021", "POPESTIMATE2022", "POPESTIMATE2023", "POPESTIMATE2024"]].mean()
pop_trend_q4 = city_pop_q4_df[["POPESTIMATE2020", "POPESTIMATE2021", "POPESTIMATE2022", "POPESTIMATE2023", "POPESTIMATE2024"]].mean()
#Combine series into trends df
pop_trends_df = pd.DataFrame({"Q1":pop_trend_q1, "Q2":pop_trend_q2, "Q3":pop_trend_q3, "Q4":pop_trend_q4})
#Set Year as index for chart
pop_trends_df_reset = pop_trends_df.reset_index().rename(columns={"index":"Year"})
#Create chart
alt.Chart(pop_trends_df_reset).transform_fold(
    ["Q1", "Q2", "Q3", "Q4"],
    as_=["Quartile", "AvgPopulation"]
).mark_line(point=True).encode(
    x="Year:O",
    y="AvgPopulation:Q",
    color="Quartile:N"
)

alt.Chart(...)

In [48]:
# Load Single Family Home Data From Zillow
hv_df = pd.read_csv('Data/Metro_zhvi_uc_sfr_tier_0.33_0.67_sm_sa_month.csv')
hv_df = hv_df.dropna().reset_index(drop=True)
hv_df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31
0,394913,1,"New York, NY",msa,NY,216204.906949,217118.726894,218037.699710,219896.351318,221811.278678,...,702182.814240,704969.033163,707107.919763,708900.805287,710150.247552,710896.834350,712302.053289,714730.852730,718376.989056,722152.928657
1,753899,2,"Los Angeles, CA",msa,CA,229297.470433,230172.549865,231311.720436,233582.033926,236045.928058,...,999743.331098,995425.637330,990670.231609,986095.146144,983311.895154,981993.638461,983107.386702,985799.648759,989828.455467,994554.776693
2,394463,3,"Chicago, IL",msa,IL,155779.960126,155931.205194,156209.724698,156902.542597,157730.488497,...,343920.881014,344749.181516,345226.838090,345740.750099,346716.042282,347812.294196,349197.912152,350501.179573,352118.031490,354044.365771
3,394692,5,"Houston, TX",msa,TX,124201.785021,124222.275651,124132.587009,124187.678168,124237.524336,...,311422.028483,310507.749997,309567.114049,308577.371747,307742.508535,307038.679976,306588.438186,306205.991455,306032.499583,306061.376066
4,395209,6,"Washington, DC",msa,VA,190554.271674,190724.956272,191018.183957,191687.549705,192690.707732,...,613647.858539,613390.166609,612066.818598,610552.119406,609282.350791,608480.941311,608399.190942,608991.010218,610130.502925,611293.161618

In [22]:
#Exploratory analysis on SF home data
#Creat subset of SF Home Data that contains average home value per year
yearly_hv_df = hv_df[["RegionID", "RegionName"]].copy()
#Add 2020 column
yearly_hv_df["2020"] = hv_df.filter(like="2020").mean(axis=1)
#Add 2021 column
yearly_hv_df["2021"] = hv_df.filter(like="2021").mean(axis=1)
#Add 2022 column
yearly_hv_df["2022"] = hv_df.filter(like="2022").mean(axis=1)
#Add 2023 column
yearly_hv_df["2023"] = hv_df.filter(like="2023").mean(axis=1)
#Add 2024 column
yearly_hv_df["2024"] = hv_df.filter(like="2024").mean(axis=1)
#Describe single family home value dataframe
yearly_hv_df[["2020", "2021", "2022", "2023", "2024"]].describe()

                2020          2021          2022          2023          2024
count     303.000000  3.030000e+02  3.030000e+02  3.030000e+02  3.030000e+02
mean   237725.882405  2.763074e+05  3.162220e+05  3.233422e+05  3.367307e+05
std    148027.712157  1.742300e+05  2.031868e+05  2.008187e+05  2.094643e+05
min     72347.361015  7.900944e+04  8.256555e+04  8.160028e+04  8.117405e+04
25%    139801.111790  1.628118e+05  1.802297e+05  1.864407e+05  1.955466e+05
50%    195063.507799  2.251554e+05  2.593602e+05  2.686258e+05  2.832674e+05
75%    275449.819907  3.306017e+05  3.783997e+05  3.889072e+05  4.028104e+05
max    975942.963809  1.133728e+06  1.391799e+06  1.427432e+06  1.507342e+06

In [34]:
#Trend line of SF home prices per year by quartile
#Create subdataframes for each quartile of yearly_hv_df
yearly_hv_q1_df = yearly_hv_df[yearly_hv_df["2020"] <= 139801.111790].reset_index(drop=True)
yearly_hv_q2_df = yearly_hv_df[(yearly_hv_df["2020"] <= 195063.507799) & (yearly_hv_df["2020"] > 139801.111790)].reset_index(drop=True)
yearly_hv_q3_df = yearly_hv_df[(yearly_hv_df["2020"] <= 275449.819907) & (yearly_hv_df["2020"] > 195063.507799)].reset_index(drop=True)
yearly_hv_q4_df = yearly_hv_df[yearly_hv_df["2020"] > 275449.819907].reset_index(drop=True)
#Create trend series of averages per year
hv_trend_q1 = yearly_hv_q1_df[["2020", "2021", "2022", "2023", "2024"]].mean()
hv_trend_q2 = yearly_hv_q2_df[["2020", "2021", "2022", "2023", "2024"]].mean()
hv_trend_q3 = yearly_hv_q3_df[["2020", "2021", "2022", "2023", "2024"]].mean()
hv_trend_q4 = yearly_hv_q4_df[["2020", "2021", "2022", "2023", "2024"]].mean()
#Combine series into trends df
hv_trends_df = pd.DataFrame({"Q1":hv_trend_q1, "Q2":hv_trend_q2, "Q3":hv_trend_q3, "Q4":hv_trend_q4})
#Set Year as index for chart
hv_trends_df_reset = hv_trends_df.reset_index().rename(columns={"index":"Year"})
#Create chart
alt.Chart(hv_trends_df_reset).transform_fold(
    ["Q1", "Q2", "Q3", "Q4"],
    as_=["Quartile", "AvgHomeValue"]
).mark_line(point=True).encode(
    x="Year:O",
    y="AvgHomeValue:Q",
    color="Quartile:N"
)

alt.Chart(...)

In [35]:
# Load Rental Data from Zillow 
rent_df = pd.read_csv('Data/Metro_zori_uc_sfr_sm_month.csv')
rent_df = rent_df.dropna().reset_index(drop=True)
rent_df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,...,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31
0,394913,1,"New York, NY",msa,NY,2051.900538,2073.674430,2091.698696,2102.985678,2104.583143,...,3419.456502,3440.434907,3475.028422,3493.461389,3499.061761,3505.398741,3498.478094,3506.189548,3520.638335,3527.294931
1,394463,3,"Chicago, IL",msa,IL,1412.925074,1419.169659,1427.120371,1439.497223,1450.368984,...,2320.172452,2335.313483,2346.684808,2355.452452,2373.809321,2378.700139,2385.748292,2378.994134,2378.676689,2375.586810
2,394514,4,"Dallas, TX",msa,TX,1362.956873,1371.226470,1381.051439,1394.360523,1406.557582,...,2301.402813,2312.824302,2316.975073,2319.425134,2316.686754,2309.203411,2307.348452,2305.694747,2302.928515,2297.098763
3,394692,5,"Houston, TX",msa,TX,1500.342979,1504.189431,1511.687962,1523.017552,1535.161535,...,2142.268237,2152.016809,2156.772453,2155.041635,2154.975617,2154.527876,2154.179611,2150.218149,2146.573017,2143.428600
4,395209,6,"Washington, DC",msa,VA,2004.611050,2018.661812,2035.216619,2046.197035,2054.206122,...,3060.815425,3070.451335,3077.083525,3080.365874,3092.832357,3098.658028,3100.453179,3085.716857,3076.398213,3066.136184

In [66]:
#Exploratory analysis on rental data
#Creat subset of Rental Data that contains average rent per year
yearly_rent_df = rent_df[["RegionID", "RegionName", "StateName"]].copy()
#Add 2020 column
yearly_rent_df["2020"] = rent_df.filter(like="2020").mean(axis=1)
#Add 2021 column
yearly_rent_df["2021"] = rent_df.filter(like="2021").mean(axis=1)
#Add 2022 column
yearly_rent_df["2022"] = rent_df.filter(like="2022").mean(axis=1)
#Add 2023 column
yearly_rent_df["2023"] = rent_df.filter(like="2023").mean(axis=1)
#Add 2024 column
yearly_rent_df["2024"] = rent_df.filter(like="2024").mean(axis=1)
#Describe single family home value dataframe
yearly_rent_df[["2020", "2021", "2022", "2023", "2024"]].describe()

              2020         2021         2022         2023         2024
count   170.000000   170.000000   170.000000   170.000000   170.000000
mean   1510.324876  1669.809247  1853.479172  1956.135796  2043.088275
std     487.498129   523.677857   578.228134   603.206092   623.103375
min     734.584587   822.005395   899.013259   939.002971  1028.309202
25%    1163.080643  1263.665985  1396.846883  1496.086591  1572.416758
50%    1439.596520  1610.549580  1800.861805  1900.300242  2004.225694
75%    1690.859386  1872.164645  2077.839333  2215.378398  2307.169579
max    3644.609486  3693.062461  3907.239043  4051.470416  4220.636867

In [67]:
#Trend line of rent per year by quartile
#Create subdataframes for each quartile of yearly_rent_df
yearly_rent_q1_df = yearly_rent_df[yearly_rent_df["2020"] <= 1163.080643].reset_index(drop=True)
yearly_rent_q2_df = yearly_rent_df[(yearly_rent_df["2020"] <= 1439.596520) & (yearly_rent_df["2020"] > 1163.080643)].reset_index(drop=True)
yearly_rent_q3_df = yearly_rent_df[(yearly_rent_df["2020"] <= 1690.859386) & (yearly_rent_df["2020"] > 1439.596520)].reset_index(drop=True)
yearly_rent_q4_df = yearly_rent_df[yearly_rent_df["2020"] > 1690.859386].reset_index(drop=True)
#Create trend series of averages per year
rent_trend_q1 = yearly_rent_q1_df[["2020", "2021", "2022", "2023", "2024"]].mean()
rent_trend_q2 = yearly_rent_q2_df[["2020", "2021", "2022", "2023", "2024"]].mean()
rent_trend_q3 = yearly_rent_q3_df[["2020", "2021", "2022", "2023", "2024"]].mean()
rent_trend_q4 = yearly_rent_q4_df[["2020", "2021", "2022", "2023", "2024"]].mean()
#Combine series into trends df
rent_trends_df = pd.DataFrame({"Q1":rent_trend_q1, "Q2":rent_trend_q2, "Q3":rent_trend_q3, "Q4":rent_trend_q4})
#Set Year as index for chart
rent_trends_df_reset = rent_trends_df.reset_index().rename(columns={"index":"Year"})
#Create chart
alt.Chart(rent_trends_df_reset).transform_fold(
    ["Q1", "Q2", "Q3", "Q4"],
    as_=["Quartile", "AvgRent"]
).mark_line(point=True).encode(
    x="Year:O",
    y="AvgRent:Q",
    color="Quartile:N"
)

alt.Chart(...)

In [72]:
#Load Residential Construction Permits
permits_df = pd.read_csv('Data/Residential_Construction_Permits_by_County_5026727375813176131.csv')
permits_df.head()

,OBJECTID,GEOID,STATE,COUNTY,NAME,STUSAB,STATE_NAME,ALL_PERMITS_1980,SINGLE_FAMILY_PERMITS_1980,ALL_MULTIFAMILY_PERMITS_1980,...,MULTIFAMILY_PERMITS_3_4_UNITS_2021,MULTIFAMILY_PERMITS_5_OR_MORE_UNITS_2021,ALL_PERMITS_2022,SINGLE_FAMILY_PERMITS_2022,ALL_MULTIFAMILY_PERMITS_2022,MULTIFAMILY_PERMITS_2_UNITS_2022,MULTIFAMILY_PERMITS_3_4_UNIT_2022,MULTIFAMILY_PERMITS_5_OR_MORE_2022,Shape__Area,Shape__Length
0,1,53021,53,21,Franklin,WA,Washington,185.0,81.0,104.0,...,0,5,644.0,423.0,221.0,16.0,4.0,201.0,6.923130e+09,4.260543e+05
1,2,4017,4,17,Navajo,AZ,Arizona,563.0,511.0,52.0,...,8,0,580.0,568.0,12.0,8.0,4.0,0.0,3.892301e+10,1.146737e+06
2,3,49051,49,51,Wasatch,UT,Utah,106.0,104.0,2.0,...,0,277,1009.0,991.0,18.0,0.0,6.0,12.0,5.381082e+09,4.365787e+05
3,4,49033,49,33,Rich,UT,Utah,48.0,48.0,NaN,...,0,0,71.0,71.0,0.0,0.0,0.0,0.0,5.040539e+09,3.993842e+05
4,5,49043,49,43,Summit,UT,Utah,525.0,294.0,231.0,...,30,123,560.0,470.0,90.0,0.0,0.0,90.0,8.532140e+09,6.285718e+05

In [80]:
#Exploratory Data Analysis on Permits dataset
#Create subset of dataframe contains columns for single family permits from 2020-2022
recent_permits_df = permits_df[["COUNTY", "NAME", "STUSAB", "STATE_NAME", "SINGLE_FAMILY_PERMITS_2020", "SINGLE_FAMILY_PERMITS_2021", "SINGLE_FAMILY_PERMITS_2022"]].copy()
recent_permits_df = recent_permits_df.reset_index(drop=True)
#Remove records with null values
recent_permits_df = recent_permits_df.dropna().reset_index(drop=True)
#Describe recent permits df
recent_permits_df[["SINGLE_FAMILY_PERMITS_2020", "SINGLE_FAMILY_PERMITS_2021", "SINGLE_FAMILY_PERMITS_2022"]].describe()

,SINGLE_FAMILY_PERMITS_2020,SINGLE_FAMILY_PERMITS_2021,SINGLE_FAMILY_PERMITS_2022
count,2662.000000,2662.000000,2662.000000
mean,367.787754,418.611570,366.153644
std,1136.622024,1267.062553,1078.375262
min,1.000000,0.000000,0.000000
25%,15.000000,16.000000,17.000000
50%,64.000000,71.000000,68.000000
75%,227.000000,265.000000,246.000000
max,25526.000000,26069.000000,20608.000000

In [82]:
#Trend line of permits per year by quartile
#Create subdataframes for each quartile of recent_permits_df
permits_q1_df = recent_permits_df[recent_permits_df["SINGLE_FAMILY_PERMITS_2020"] <= 15.000000].reset_index(drop=True)
permits_q2_df = recent_permits_df[(recent_permits_df["SINGLE_FAMILY_PERMITS_2020"] <= 64.000000) & (recent_permits_df["SINGLE_FAMILY_PERMITS_2020"] > 15.000000)].reset_index(drop=True)
permits_q3_df = recent_permits_df[(recent_permits_df["SINGLE_FAMILY_PERMITS_2020"] <= 227.000000) & (recent_permits_df["SINGLE_FAMILY_PERMITS_2020"] > 64.000000)].reset_index(drop=True)
permits_q4_df = recent_permits_df[recent_permits_df["SINGLE_FAMILY_PERMITS_2020"] > 227.000000].reset_index(drop=True)
#Create trend series of averages per year
permits_trend_q1 = permits_q1_df[["SINGLE_FAMILY_PERMITS_2020", "SINGLE_FAMILY_PERMITS_2021", "SINGLE_FAMILY_PERMITS_2022"]].mean()
permits_trend_q2 = permits_q2_df[["SINGLE_FAMILY_PERMITS_2020", "SINGLE_FAMILY_PERMITS_2021", "SINGLE_FAMILY_PERMITS_2022"]].mean()
permits_trend_q3 = permits_q3_df[["SINGLE_FAMILY_PERMITS_2020", "SINGLE_FAMILY_PERMITS_2021", "SINGLE_FAMILY_PERMITS_2022"]].mean()
permits_trend_q4 = permits_q4_df[["SINGLE_FAMILY_PERMITS_2020", "SINGLE_FAMILY_PERMITS_2021", "SINGLE_FAMILY_PERMITS_2022"]].mean()
#Combine series into trends df
permit_trends_df = pd.DataFrame({"Q1":permits_trend_q1, "Q2":permits_trend_q2, "Q3":permits_trend_q3, "Q4":permits_trend_q4})
#Set Year as index for chart
permit_trends_df_reset = permit_trends_df.reset_index().rename(columns={"index":"Year"})
#Create chart
alt.Chart(permit_trends_df_reset).transform_fold(
    ["Q1", "Q2", "Q3", "Q4"],
    as_=["Quartile", "AvgPermits"]
).mark_line(point=True).encode(
    x="Year:O",
    y="AvgPermits:Q",
    color="Quartile:N"
)

alt.Chart(...)

In [69]:
#Load Housing Characteristics (2020-2024)
houseChar_df = pd.read_csv('Data/ACS_5YR_Housing_Estimate_Data_by_State_-5633158829445399210.csv')
houseChar_df.head()

,OBJECTID_1,GEOID,STUSAB,NAME,B25002EST1,B25002EST2,B25002EST2_PCT,B25002EST3,B25002EST3_PCT,B25009EST2,...,B25123EST10,B25123EST10_PCT,B25123EST11,B25123EST11_PCT,B25123EST12,B25123EST12_PCT,B25123EST13,B25123EST13_PCT,Shape__Area,Shape__Length
0,1,17,IL,Illinois,5373385,4884061,90.89,489324,9.11,3237778,...,47188,2.87,2223,0.14,30,0.00,905096,54.98,2.496598e+11,2.780939e+06
1,2,18,IN,Indiana,2903720,2602770,89.64,300950,10.36,1808293,...,16973,2.14,827,0.10,98,0.01,451601,56.84,1.595740e+11,2.248208e+06
2,3,20,KS,Kansas,1280376,1141985,89.19,138391,10.81,756309,...,10203,2.65,465,0.12,12,0.00,225923,58.58,3.484440e+11,2.570737e+06
3,4,21,KY,Kentucky,1994554,1748053,87.64,246501,12.36,1181021,...,13871,2.45,719,0.13,217,0.04,341525,60.23,1.667056e+11,2.749110e+06
4,5,22,LA,Louisiana,2074664,1751956,84.45,322708,15.55,1167628,...,15499,2.65,475,0.08,105,0.02,305831,52.34,1.657292e+11,1.632256e+07

In [84]:
#Load 30yr Interest Rates
intRates_df = pd.read_csv('https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=MORTGAGE30US&scale=left&cosd=1971-04-02&coed=2026-02-12&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Weekly%2C%20Ending%20Thursday&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-02-14&revision_date=2026-02-14&nd=1971-04-02')
intRates_df.head()

  observation_date  MORTGAGE30US
0       1971-04-02          7.33
1       1971-04-09          7.31
2       1971-04-16          7.31
3       1971-04-23          7.31
4       1971-04-30          7.29

In [89]:
#Exploratory Data Analysis on Interest Rates
#Creat subset of Interest Rates that contains average interest rate per year
yearly_intRate_df = intRates_df.copy()
#Add year column for aggregation
yearly_intRate_df["observation_date"] = pd.to_datetime(yearly_intRate_df["observation_date"])
yearly_intRate_df["year"] = yearly_intRate_df["observation_date"].dt.year
#Group by year
yearly_intRate_df = yearly_intRate_df.groupby("year")["MORTGAGE30US"].mean().reset_index()
yearly_intRate_df.rename(columns={"MORTGAGE30US":"Avg30yrInterest_Rate"}, inplace=True)
#Reduce to 2020-2024
yearly_intRate_df = yearly_intRate_df[(yearly_intRate_df["year"] >= 2020) & (yearly_intRate_df["year"] < 2025)].reset_index(drop=True)
#Describe yearly interest rate dataframe
yearly_intRate_df[["Avg30yrInterest_Rate"]].describe()

       Avg30yrInterest_Rate
count              5.000000
mean               4.988263
std                1.876235
min                2.957692
25%                3.111698
50%                5.344038
75%                6.721154
max                6.806731

In [90]:
#Create trend line chart
alt.Chart(yearly_intRate_df).mark_line(point=True).encode(x="year:O", y="Avg30yrInterest_Rate:Q")

alt.Chart(...)

<strong>Inter-Tabular Exploratory Data Analysis</strong>

In [70]:
#Key table to link state name abbreviation to full name
state_name_key_df = houseChar_df[["STUSAB", "NAME"]].copy()
state_name_key_df = state_name_key_df.reset_index(drop=True)
state_name_key_df.head()

  STUSAB       NAME
0     IL   Illinois
1     IN    Indiana
2     KS     Kansas
3     KY   Kentucky
4     LA  Louisiana